# Generated by Django 4.2.6 on 2023-11-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='users/%Y', verbose_name='Фотография'),
        ),
    ]
