# Generated by Django 4.2.6 on 2023-11-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Наименование категории')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('image', models.ImageField(default='no_image.png', upload_to='media/')),
            ],
            options={
                'verbose_name': 'Категория продукции',
                'verbose_name_plural': 'Категории продукции',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('email', models.EmailField(max_length=128, verbose_name='Электронный адрес (email)')),
                ('contact_number', models.CharField(max_length=12, unique=True, verbose_name='Контактный номер')),
                ('comment', models.TextField(verbose_name='Содержание послания')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Наименование')),
                ('designation', models.CharField(max_length=64, verbose_name='Обозначение')),
                ('material', models.CharField(max_length=64, verbose_name='Материал')),
                ('units_of_measure', models.CharField(choices=[('шт.', 'шт.'), ('пог. м.', 'пог. м.'), ('кв. м.', 'кв. м.'), ('т.', 'т.')], default='т.', max_length=8, verbose_name='Единица измерения')),
                ('price_for_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за единицу')),
                ('in_stock', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='На складе')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='Наличие')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home_app.category')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
                'ordering': ('designation',),
            },
        ),
    ]
