# Generated by Django 4.2.6 on 2023-10-12 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Наименование категории')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('image', models.ImageField(upload_to='products/')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продуктов',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Наименование')),
                ('designation', models.CharField(max_length=64, verbose_name='Обозначение')),
                ('material', models.CharField(max_length=64, verbose_name='Материал')),
                ('units_of_measure', models.CharField(choices=[('EA', 'шт.'), ('LIN_M', 'пог. м.'), ('SQ_M', 'кв. м.'), ('T', 'т.')], default='T', max_length=8, verbose_name='Единица измерения')),
                ('price_for_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за единицу')),
                ('in_stock', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='На складе')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='Наличие')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home_app.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('title',),
            },
        ),
    ]
