# Generated by Django 4.2.6 on 2023-11-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('price_file', models.FileField(default='test_price.pdf', null=True, upload_to='home_app/%Y', verbose_name='Актуальный прайс')),
            ],
        ),
    ]
