# Generated by Django 4.2.6 on 2023-10-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('slug',), 'verbose_name': 'Категория продукции', 'verbose_name_plural': 'Категории продукции'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'Продукция'},
        ),
    ]
