# Generated by Django 4.2.6 on 2023-11-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_fileprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileprice',
            options={'ordering': ['-time_create'], 'verbose_name': 'Prices', 'verbose_name_plural': 'Price'},
        ),
    ]
