# Generated by Django 4.2.6 on 2023-10-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('email', models.EmailField(max_length=128, verbose_name='Электронный адрес (email)')),
                ('contact_number', models.SlugField(unique=True, verbose_name='Контактный номер')),
                ('comment', models.TextField(verbose_name='Содержание послания')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'ordering': ['-time_create'],
            },
        ),
    ]
