# Generated by Django 4.2.6 on 2023-10-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-time_create'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукция'},
        ),
    ]
