# Generated by Django 4.2.6 on 2023-10-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_alter_feedback_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('designation',), 'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукция'},
        ),
    ]
