# Generated by Django 4.2.6 on 2023-10-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units_of_measure',
            field=models.CharField(choices=[('шт.', 'шт.'), ('пог. м.', 'пог. м.'), ('кв. м.', 'кв. м.'), ('т.', 'т.')], default='т.', max_length=8, verbose_name='Единица измерения'),
        ),
    ]
